export const initialState = {
    listPet: [
        {
            petId: 1,
            petName: "Diva",
            petImageUrls: "https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg?crop=0.752xw:1.00xh;0.175xw,0&resize=1200:*",
            gender: "Cái",
            color: "Nâu nhạt",
            description: "Xin giới thiệu Diva - một chú chó có cái tên như tính cách của bạn ấy! Cô chó trẻ trung này cá tính và tràn đầy năng lượng, sẵn sàng thắp sáng bất kỳ căn phòng nào bạn ấy bước vào. Với bản tính tự tin và hướng ngoại, Diva thích trở thành trung tâm của sự chú ý, nơi bạn ấy có thể tương tác với mọi người và nhận được tất cả tình yêu thương mà bạn ấy khao khát. Tinh thần vui tươi của bạn ấy chắc chắn sẽ chinh phục bạn.",
            foodPreferences: null,
            toyPreferences: null,
            compatibleWith: "Diva sẽ phát triển tốt nhất trong một môi trường yêu thương, nơi bạn ấy là trung tâm của sự chú ý và có thể nhận được nhiều tình cảm và thời gian vui chơi.Diva sẽ cần một ngôi nhà nơi bạn ấy là chú chó duy nhất hoặc một ngôi nhà có một chú chó lớn tuổi và điềm tĩnh.Diva sẽ cần được chải long thường xuyên để đảm bảo bộ lông mềm mại của bạn ấy luôn trong tình trạng tốt.Diva sẽ cần một ngôi nhà có sân an toàn.",
            notCompatibleWith: null,
            location: "Thủ Đức",
            categoryId: 1,
            categoryName: "Chó",
            breedId: 1,
            breed: "Chó Poodle",
            age: 12,
            size: "Trung bình",
            weight: 5.2,
            isVaccinated: true,
            isNeutered: true,
            isTrained: false,
            healthStatus: "Khỏe mạnh",
            personality: "Thân thiện, năng động",
            adoptionStatus: "Available",
            isVerified: true,
            verificationStatus: "verified",
            ownerId: 101,
            ownerName: "Nguyễn Văn A",
            ownerEmail: "nguyenvana@example.com",
            ownerPhone: "0901234567",
            createdDate: "2025-05-10T10:30:00Z",
            slug: "diva-1"
        },
        {
            petId: 2,
            petName: "Luna",
            petImageUrls: "/placeholder.svg?height=300&width=300",
            gender: "Cái",
            color: "Đen trắng",
            description: "Luna là một con mèo xiêm rất dịu dàng và thông minh.",
            foodPreferences: "Thức ăn khô cao cấp",
            toyPreferences: "Đồ chơi chuột nhỏ",
            compatibleWith: "Luna thích ở trong môi trường yên tĩnh và thích được vuốt ve.",
            notCompatibleWith: "Không thích chó và trẻ em ồn ào",
            location: "Quận 1",
            categoryId: 2,
            categoryName: "Mèo",
            breedId: 5,
            breed: "Mèo Xiêm",
            age: 24,
            size: "Nhỏ",
            weight: 3.5,
            isVaccinated: true,
            isNeutered: true,
            isTrained: true,
            healthStatus: "Khỏe mạnh",
            personality: "Điềm tĩnh, thông minh",
            adoptionStatus: "Pending",
            isVerified: false,
            verificationStatus: "pending_verification",
            ownerId: 102,
            ownerName: "Trần Thị B",
            ownerEmail: "tranthib@example.com",
            ownerPhone: "0909876543",
            createdDate: "2025-05-15T14:20:00Z",
            slug: "luna-2"
        },
        {
            petId: 3,
            petName: "Rocky",
            petImageUrls: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGRvZ3xlbnwwfHwwfHx8MA%3D%3D",
            gender: "Đực",
            color: "Nâu đen",
            description: "Rocky là một chú chó Labrador khỏe mạnh và rất thân thiện với trẻ em.",
            foodPreferences: "Thức ăn tươi và khô",
            toyPreferences: "Bóng và đồ chơi gặm",
            compatibleWith: "Rocky rất thân thiện với mọi người và thú cưng khác.",
            notCompatibleWith: null,
            location: "Quận 7",
            categoryId: 1,
            categoryName: "Chó",
            breedId: 2,
            breed: "Chó Labrador",
            age: 18,
            size: "Lớn",
            weight: 25.5,
            isVaccinated: true,
            isNeutered: true,
            isTrained: true,
            healthStatus: "Khỏe mạnh",
            personality: "Hoạt bát, thân thiện",
            adoptionStatus: "Available",
            isVerified: false,
            verificationStatus: "pending_verification",
            ownerId: 103,
            ownerName: "Lê Văn C",
            ownerEmail: "levanc@example.com",
            ownerPhone: "0977123456",
            createdDate: "2025-05-18T09:15:00Z",
            slug: "rocky-3"
        },
        {
            petId: 4,
            petName: "Rocky",
            petImageUrls: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGRvZ3xlbnwwfHwwfHx8MA%3D%3D",
            gender: "Đực",
            color: "Nâu đen",
            description: "Rocky là một chú chó Labrador khỏe mạnh và rất thân thiện với trẻ em.",
            foodPreferences: "Thức ăn tươi và khô",
            toyPreferences: "Bóng và đồ chơi gặm",
            compatibleWith: "Rocky rất thân thiện với mọi người và thú cưng khác.",
            notCompatibleWith: null,
            location: "Quận 7",
            categoryId: 1,
            categoryName: "Chó",
            breedId: 2,
            breed: "Chó Labrador",
            age: 18,
            size: "Lớn",
            weight: 25.5,
            isVaccinated: true,
            isNeutered: true,
            isTrained: true,
            healthStatus: "Khỏe mạnh",
            personality: "Hoạt bát, thân thiện",
            adoptionStatus: "Available",
            isVerified: false,
            verificationStatus: "pending_verification",
            ownerId: 103,
            ownerName: "Lê Văn C",
            ownerEmail: "levanc@example.com",
            ownerPhone: "0977123456",
            createdDate: "2025-05-18T09:15:00Z",
            slug: "rocky-3"
        },
        {
            petId: 5,
            petName: "Rocky",
            petImageUrls: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGRvZ3xlbnwwfHwwfHx8MA%3D%3D",
            gender: "Đực",
            color: "Nâu đen",
            description: "Rocky là một chú chó Labrador khỏe mạnh và rất thân thiện với trẻ em.",
            foodPreferences: "Thức ăn tươi và khô",
            toyPreferences: "Bóng và đồ chơi gặm",
            compatibleWith: "Rocky rất thân thiện với mọi người và thú cưng khác.",
            notCompatibleWith: null,
            location: "Quận 7",
            categoryId: 1,
            categoryName: "Chó",
            breedId: 2,
            breed: "Chó Labrador",
            age: 18,
            size: "Lớn",
            weight: 25.5,
            isVaccinated: true,
            isNeutered: true,
            isTrained: true,
            healthStatus: "Khỏe mạnh",
            personality: "Hoạt bát, thân thiện",
            adoptionStatus: "Available",
            isVerified: false,
            verificationStatus: "pending_verification",
            ownerId: 103,
            ownerName: "Lê Văn C",
            ownerEmail: "levanc@example.com",
            ownerPhone: "0977123456",
            createdDate: "2025-05-18T09:15:00Z",
            slug: "rocky-3"
        },
        {
            petId: 6,
            petName: "Rocky",
            petImageUrls: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGRvZ3xlbnwwfHwwfHx8MA%3D%3D",
            gender: "Đực",
            color: "Nâu đen",
            description: "Rocky là một chú chó Labrador khỏe mạnh và rất thân thiện với trẻ em.",
            foodPreferences: "Thức ăn tươi và khô",
            toyPreferences: "Bóng và đồ chơi gặm",
            compatibleWith: "Rocky rất thân thiện với mọi người và thú cưng khác.",
            notCompatibleWith: null,
            location: "Quận 7",
            categoryId: 1,
            categoryName: "Chó",
            breedId: 2,
            breed: "Chó Labrador",
            age: 18,
            size: "Lớn",
            weight: 25.5,
            isVaccinated: true,
            isNeutered: true,
            isTrained: true,
            healthStatus: "Khỏe mạnh",
            personality: "Hoạt bát, thân thiện",
            adoptionStatus: "Available",
            isVerified: false,
            verificationStatus: "pending_verification",
            ownerId: 103,
            ownerName: "Lê Văn C",
            ownerEmail: "levanc@example.com",
            ownerPhone: "0977123456",
            createdDate: "2025-05-18T09:15:00Z",
            slug: "rocky-3"
        },
        {
            petId: 7,
            petName: "Rocky",
            petImageUrls: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGRvZ3xlbnwwfHwwfHx8MA%3D%3D",
            gender: "Đực",
            color: "Nâu đen",
            description: "Rocky là một chú chó Labrador khỏe mạnh và rất thân thiện với trẻ em.",
            foodPreferences: "Thức ăn tươi và khô",
            toyPreferences: "Bóng và đồ chơi gặm",
            compatibleWith: "Rocky rất thân thiện với mọi người và thú cưng khác.",
            notCompatibleWith: null,
            location: "Quận 7",
            categoryId: 1,
            categoryName: "Chó",
            breedId: 2,
            breed: "Chó Labrador",
            age: 18,
            size: "Lớn",
            weight: 25.5,
            isVaccinated: true,
            isNeutered: true,
            isTrained: true,
            healthStatus: "Khỏe mạnh",
            personality: "Hoạt bát, thân thiện",
            adoptionStatus: "Available",
            isVerified: false,
            verificationStatus: "pending_verification",
            ownerId: 103,
            ownerName: "Lê Văn C",
            ownerEmail: "levanc@example.com",
            ownerPhone: "0977123456",
            createdDate: "2025-05-18T09:15:00Z",
            slug: "rocky-3"
        },
        {
            petId: 8,
            petName: "Rocky",
            petImageUrls: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGRvZ3xlbnwwfHwwfHx8MA%3D%3D",
            gender: "Đực",
            color: "Nâu đen",
            description: "Rocky là một chú chó Labrador khỏe mạnh và rất thân thiện với trẻ em.",
            foodPreferences: "Thức ăn tươi và khô",
            toyPreferences: "Bóng và đồ chơi gặm",
            compatibleWith: "Rocky rất thân thiện với mọi người và thú cưng khác.",
            notCompatibleWith: null,
            location: "Quận 7",
            categoryId: 1,
            categoryName: "Chó",
            breedId: 2,
            breed: "Chó Labrador",
            age: 18,
            size: "Lớn",
            weight: 25.5,
            isVaccinated: true,
            isNeutered: true,
            isTrained: true,
            healthStatus: "Khỏe mạnh",
            personality: "Hoạt bát, thân thiện",
            adoptionStatus: "Available",
            isVerified: false,
            verificationStatus: "pending_verification",
            ownerId: 103,
            ownerName: "Lê Văn C",
            ownerEmail: "levanc@example.com",
            ownerPhone: "0977123456",
            createdDate: "2025-05-18T09:15:00Z",
            slug: "rocky-3"
        },
        {
            petId: 9,
            petName: "Rocky",
            petImageUrls: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGRvZ3xlbnwwfHwwfHx8MA%3D%3D",
            gender: "Đực",
            color: "Nâu đen",
            description: "Rocky là một chú chó Labrador khỏe mạnh và rất thân thiện với trẻ em.",
            foodPreferences: "Thức ăn tươi và khô",
            toyPreferences: "Bóng và đồ chơi gặm",
            compatibleWith: "Rocky rất thân thiện với mọi người và thú cưng khác.",
            notCompatibleWith: null,
            location: "Quận 7",
            categoryId: 1,
            categoryName: "Chó",
            breedId: 2,
            breed: "Chó Labrador",
            age: 18,
            size: "Lớn",
            weight: 25.5,
            isVaccinated: true,
            isNeutered: true,
            isTrained: true,
            healthStatus: "Khỏe mạnh",
            personality: "Hoạt bát, thân thiện",
            adoptionStatus: "Available",
            isVerified: false,
            verificationStatus: "pending_verification",
            ownerId: 103,
            ownerName: "Lê Văn C",
            ownerEmail: "levanc@example.com",
            ownerPhone: "0977123456",
            createdDate: "2025-05-18T09:15:00Z",
            slug: "rocky-3"
        },
        {
            petId: 10,
            petName: "Rocky",
            petImageUrls: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGRvZ3xlbnwwfHwwfHx8MA%3D%3D",
            gender: "Đực",
            color: "Nâu đen",
            description: "Rocky là một chú chó Labrador khỏe mạnh và rất thân thiện với trẻ em.",
            foodPreferences: "Thức ăn tươi và khô",
            toyPreferences: "Bóng và đồ chơi gặm",
            compatibleWith: "Rocky rất thân thiện với mọi người và thú cưng khác.",
            notCompatibleWith: null,
            location: "Quận 7",
            categoryId: 1,
            categoryName: "Chó",
            breedId: 2,
            breed: "Chó Labrador",
            age: 18,
            size: "Lớn",
            weight: 25.5,
            isVaccinated: true,
            isNeutered: true,
            isTrained: true,
            healthStatus: "Khỏe mạnh",
            personality: "Hoạt bát, thân thiện",
            adoptionStatus: "Available",
            isVerified: false,
            verificationStatus: "pending_verification",
            ownerId: 103,
            ownerName: "Lê Văn C",
            ownerEmail: "levanc@example.com",
            ownerPhone: "0977123456",
            createdDate: "2025-05-18T09:15:00Z",
            slug: "rocky-3"
        },
    ],
    petCategories: [
        {
            categoryId: 1,
            categoryName: "Chó",
            description: "Các loại vật nuôi thuộc giống chó"
        },
        {
            categoryId: 2,
            categoryName: "Mèo",
            description: "Các loại mèo nuôi trong nhà"
        },
    ],
    petsNeedingVerification: [],
};
